### PR TITLE
https://github.com/snyk/snyk/issues/225

### PR DESCRIPTION
**Pull request by brownjava**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

Fixes https://github.com/snyk/snyk/issues/225

#### Where should the reviewer start?

package.json

#### How should this be manually tested?

Run "npm pack"

#### Any background context you want to provide?

Background should be in the ticket.

#### What are the relevant tickets?

https://github.com/snyk/snyk/issues/225

### CODE REVIEW

**Comment by miiila** [comment]
Hello @brownjava, thank you very much for catching this and for suggesting a fix. It would definitely solve the issue, but we would like to use this opportunity and improve this part of the codebase.

If you would like to adjust your PR, my suggestions would be:
- remove `head.txt` and `tail.txt` and use the content as a string directly at https://github.com/snyk/snyk/blob/e862cf8fad5aa8a189c10e8cd8e910e7e58d623f/src/cli/commands/unpublished/index.js#L19-L20
- move `package-list.txt` out of `src` folder and update https://github.com/snyk/snyk/blob/e862cf8fad5aa8a189c10e8cd8e910e7e58d623f/src/cli/commands/unpublished/index.js#L14 accordingly

If you don't have a capacity or time to adjust, don't worry, we will handle this internally in the next 2 weeks.

Thank you again for your help, we really appreciate it.

**Comment by brownjava** [comment]
OK!  I've submitted a new version changed based on feedback.

**Comment by Kirill89** [comment]
@brownjava thank you for your help! I decided to move thouse constants to json file instead of txt. So, new PR created at https://github.com/snyk/snyk/pull/230

**Comment by brownjava** [comment]
Sounds good!  I'll close this PR, then.

**Pull request closed without merging**
