### PR TITLE
chore: renamed `iac drift scan` to `iac describe`

### PR DESCRIPTION
**Pull request by eliecharra**
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/CONTRIBUTING.md) rules

#### What does this PR do?

That PR just simply rename `iac drift scan` to `iac describe`

#### Where should the reviewer start?

`src/cli/commands/describe.ts`

#### How should this be manually tested?

`$ snyk iac describe`

#### What are the relevant tickets?

https://snyksec.atlassian.net/browse/CFG-1625

#### Screenshots

image

### CODE REVIEW

**Comment by eliecharra** [comment]
> Warnings
> 	
> Please make changes to `snyk help` text in [Gitbook](https://docs.snyk.io/features/snyk-cli/commands). Changes will be automatically synchronised to Snyk CLI as a [scheduled PR](https://github.com/snyk/snyk/actions/workflows/sync-cli-help-to-user-docs.yml). For more information, see: [`help/README.md`](https://github.com/snyk/snyk/tree/master/help/README.md).
> 
> Generated by no_entry_sign [dangerJS](https://danger.systems/js) against [77c07cf](https://github.com/snyk/snyk/commit/77c07cf29bb34b4b5f134d306bc5064a17b819c1)

We do not want that to be in gitbook for now (see https://github.com/snyk/snyk/pull/2780#discussion_r811901729)

**Review by moadibfr — APPROVED** [review]
LGTM nothing much to say 😅

**Review by JackuB — APPROVED** [review]
Q: this dift (sic) spec should stay as it is? https://github.com/snyk/snyk/blob/master/test/jest/acceptance/iac/dift.spec.ts

**Comment by eliecharra** [comment]
> Q: this dift (sic) spec should stay as it is? https://github.com/snyk/snyk/blob/master/test/jest/acceptance/iac/dift.spec.ts

Good question @JackuB 🙏🏻 
Event if `iac gen-driftignore` and `iac scan` will not be under `iac drift` cli namespace anymore, they are still linked to this same `drift` concept regardless of the CLI UX.
WDYT @moadibfr should we split this `drift.spec.ts` file in two parts too ?

**Pull request merged**
