### PR TITLE
fix `snyk wizard` run error on last step in npm apps or yarn apps.

### PR DESCRIPTION
**Pull request by TaopaiC**
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
When running `snyk wizard`, it fails and shows an error: `Cannot read property 'name' of undefined` at last step.

It is caused by sending incorrect information into `snyk.monitor`.

#### How should this be manually tested?

for yarn apps, we can test it in the test folder:
```
cd test/acceptance/workspaces/yarn-app
node ../../../../cli/index.js wizard
```

for npm app:
```
cd test/acceptance/workspaces/npm-package
node ../../../../cli/index.js wizard
```

### CODE REVIEW

**Comment by adrukh** [comment]
@TaopaiC thanks a lot for this!
Can you provide an example that reproduces this type of failure?

**Comment by TaopaiC** [comment]
Hi @adrukh ,

I used the npm app in `test/acceptance/workspaces/npm-package` and yarn app in `test/acceptance/workspaces/yarn-app`.

* `node -v`: v7.10.0
* `npm -v`: 4.2.0
* `yarn --version`: 0.24.6

```bash
# pctao @ Taos-MBP in ~/code/snyk on git:master o [3:55:51]
$ cd test/acceptance/workspaces/npm-package

# pctao @ Taos-MBP in ~/code/snyk/test/acceptance/workspaces/npm-package on git:master o [3:55:56]
$ npm i
npm WARN npm-package@1.0.0 No repository field.

# pctao @ Taos-MBP in ~/code/snyk/test/acceptance/workspaces/npm-package on git:master o [3:56:00]
$ node ../../../../cli/index.js wizard

Snyk's wizard will:

  * Enumerate your local dependencies and query Snyk's servers for vulnerabilities
  * Guide you through fixing found vulnerabilities
  * Create a .snyk policy file to guide snyk commands such as `test` and `protect`
  * Remember your dependencies to alert you when new vulnerabilities are disclosed

Querying vulnerabilities database...

License issues are not supported by the wizard, use `snyk ignore`

✓ Tested 0 dependencies for known vulnerabilities, no vulnerable paths found.
? Add `snyk test` to package.json file to fail test on newly disclosed vulnerabilities?
This will require authentication via `snyk auth` when running tests. No
Saving .snyk policy file...
Remembering current dependencies for future notifications...
Cannot read property 'name' of undefined
```

**Comment by adrukh** [comment]
Understood, thanks!

**Comment by adrukh** [comment]
@TaopaiC thanks again for this, it is now merged and will be released as `1.34.2` shortly.

Sorry I couldn't merge this PR as is, we have a somewhat convoluted release process for our cli. Mentioned you on the commit message https://github.com/snyk/snyk/commit/d102a6023db5485984fdae976384cfc9fa1a4b64

**Comment by TaopaiC** [comment]
Thank you :)

**Pull request closed without merging**
