### PR TITLE
fix: determine correct LockfileType for yarn v2

### PR DESCRIPTION
**Pull request by mhassan1**
- [X] Ready for review
- [X] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

Adds support for Yarn v2 with the `--yarn-workspaces` flag

#### Where should the reviewer start?

`package.json`

#### How should this be manually tested?

`snyk test --yarn-workspaces` in a Yarn v2 package that contains Yarn Workspaces

#### What are the relevant tickets?

https://github.com/snyk/snyk/issues/1322

### CODE REVIEW

**Comment by orsagie** [comment]
Hey @mhassan1 thanks for your contribution! We actually already have detection for yarn v2 in our parser, but you pointed out that we were not doing it in both `buildDepTree` methods. I added this detection in the parser, so that we don't need this extra check in the Snyk CLI : https://github.com/snyk/nodejs-lockfile-parser/pull/84. 
Once the above is merged in, let's change this PR to update the dependency of snyk-nodejs-lockfile-parser, and keep the test you added :)

**Review by orsagie — APPROVED** [review]
Big 👍

**Comment by orsagie** [comment]
closing and reopening to trigger test

**Comment by orsagie** [comment]
@mhassan1 I need to create a separate branch to trigger the tests. Can you send me your email so I can add you as contributor? to or@snyk.io

**Comment by lili2311** [comment]
@orsagie I raised a PR and cherry-picked the commit :) Closing this one

**Pull request closed without merging**
