### PR TITLE
fix: Bump @snyk/dep-graph to 1.18.3

### PR DESCRIPTION
**Pull request by rajivshah3**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
Bumps `@snyk/dep-graph` to 1.18.3

#### How should this be manually tested?
Manual testing not necessary, all unit tests pass

#### Any background context you want to provide?
`@snyk/dep-graph` accidentally included `prettier` as a `dependency` in 1.18.2, so anyone who installs the latest version of `snyk` also installs `prettier` in their `node_modules`. The latest version of `@snyk/dep-graph` moves it to a `devDependency` (https://github.com/snyk/dep-graph/commit/315b5d4fbf4e3d6f48003595b9605e95bb85849c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R38).

### CODE REVIEW

**Comment by rajivshah3** [comment]
I think I've already signed the CLA (https://github.com/snyk/snyk-sbt-plugin/pull/50#issuecomment-509035546). The CLA it's now asking me to sign actually includes a typo:
> "Snyk", "we" and "use" means Snyk Ltd.

**Comment by aviadhahami** [comment]
Hey @rajivshah3 thanks for the contribution!
I am not sure why it requires the doubly-signed CLA, I've raised this question in our internal forums :)

in the meantime - I'll amend and sign this :)

Thank you again!

**Comment by aviadhahami** [comment]
Oh, just realized it's in another repo - I'll create a new pr then :)

**Comment by aviadhahami** [comment]
Parallel PR:
https://github.com/snyk/snyk/pull/1103

**Pull request closed without merging**
