### PR TITLE
replace node-uuid with uuid

### PR DESCRIPTION
**Pull request by marudor**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?
Simple replace of the node-uuid package with uuid.
Same developer. But the name changed and node-uuid is deprecated.

### CODE REVIEW

**Comment by gjvis** [comment]
Hi @marudor, thanks for submitting this! It may take some time to review and get merged as we have a lot of things in the pipeline, but it will happen 😄

**Comment by XhmikosR** [comment]
Can this be merged? It's a pretty straight-forward change.

**Comment by adrukh** [comment]
@XhmikosR
We are working on a new release, will include this PR in it! :)

**Comment by joshje** [comment]
Hi @marudor, this is now merged into `master`: https://github.com/Snyk/snyk/commit/f67d324ff075d2df9794783501449ff5a3c6c673

**Comment by joshje** [comment]
Released as part of v1.22.0 (https://github.com/Snyk/snyk/releases/latest)

**Comment by XhmikosR** [comment]
Thanks!

**Pull request closed without merging**
