### PR TITLE
chore: delete unused code

### PR DESCRIPTION
**Pull request by sujalpatel2209**
#788
- [ ] Reviewed by Snyk internal team
- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

### CODE REVIEW

**Comment by lili2311** [comment]
@sujalpatel2209 thanks for the contribution, please could you fill out the PR template. You will also need to crop the actual file the command is loading as it won't be reachable anymore :)

**Comment by sujalpatel2209** [comment]
@lili2311 How to fill PR tamplate?

**Comment by lili2311** [comment]
- @sujalpatel2209 please click EDIT at the top there and add the details it is asking for:
Screen Shot 2019-10-07 at 10 37 08
- The file that is imported here: https://github.com/snyk/snyk/pull/789/files#diff-e64ef427412e9bab4929b8b93ca12d96L27 needs to be dropped too

**Comment by lili2311** [comment]
👋 Before we can merge this still need to drop the actual code being called, will you be able to check?

**Comment by lili2311** [comment]
@sujalpatel2209 how is this going? Let me know if you need any help :)

**Comment by lili2311** [comment]
👋 @sujalpatel2209 any luck?

**Pull request closed without merging**
