### PR TITLE
chore: Add Dockerfiles for maven 3.6.1

### PR DESCRIPTION
**Pull request by 123Haynes**
- [X] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

This PR adds 2 new Dockerfiles.
One for for maven 3.6.1 with Java 8 and one for maven 3.6.1 with java 11

Currently there is only a dockerfile for maven 3.5.4 with java 8.   
Given that there are several dockerfile for different gradle versions, I added a new Dockerfile for the latest maven version instead of updating the existing Dockerfile.

#### How should this be manually tested?

Build the Dockerfiles :smiley:  and use the image on a maven project.

#### What are the relevant tickets?

Maven 3.6.1 is the latest version of maven and Java 8 and 11 are the two most used java versions.

### CODE REVIEW

**Comment by 123Haynes** [comment]
Note that travis CI is failing because my fork does not have the necessary environment variables available.  
This is completely unrelated to the 2 new Dockerfiles.

**Comment by lili2311** [comment]
hi @123Haynes! Thank you for this. Before we can officially update & merge we will need to update our test matrix and verify java 10 & 11 is ok to verify everything is working with the plugin. Let us update that and we can then merge this awesome PR as well :)

**Comment by 123Haynes** [comment]
@lili2311 Thanks for your reply :smile: 
As a side note: I don't think it's necessary to test against java 9 and 10 anymore because they were non lts versions and reached EOL quite a while ago.
Java 9 EOL: March 2018
Java 10 EOL: September 2018  
Also these versions were not used by many people.  
If you want to support non lts versions it would make more sense to always test against the latest, officially release version of java, which is 13 at the moment.

**Comment by miiila** [comment]
Hi @123Haynes, we've recently started testing our flows on Java 11 and everything looks smooth, so we expect to review and proceed with this PR soon. Stay tuned :-) And thank you for your patience.

**Comment by miiila** [comment]
Hi @123Haynes in order to run all the tests, I merged your PR to side branch and opened new one (https://github.com/snyk/snyk/pull/718). Thank you again for this contribution, hope to see it in master soon :-)

**Pull request closed without merging**
