### PR TITLE
fix: bump snyk-go-plugin to v1.11.1

### PR DESCRIPTION
**Pull request by gitphill**
New version of snyk-go-plugin improves go modules error messaging

- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?
Bump snyk-go-plugin version

#### Any background context you want to provide?
New version improves go modules error messaging

#### What are the relevant tickets?
BST-883
https://github.com/snyk/snyk-go-plugin/pull/53

### CODE REVIEW

**Comment by dkontorovskyy** [comment]
Can you please add more info what that bump gives us?

**Comment by orsagie** [comment]
> bump gives us?

@dkontorovskyy it's in the PR message

**Comment by dkontorovskyy** [comment]
@orsagie Haven't read background context 🤦‍♂

**Comment by dkontorovskyy** [comment]
Rebase should solve the build error

**Pull request merged**
