### PR TITLE
Feat/node 6 deprecation warning

### PR DESCRIPTION
**Pull request by dkontorovskyy**
- [X] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?
Adds an EOL warning at the end of the CLI output for users that are still using Node v6.
From external contribution #803 
https://github.com/snyk/snyk/issues/787

### CODE REVIEW

**Comment by lili2311** [comment]
@dkontorovskyy looks good locally, please run the copy by Rachel?

**Comment by dkontorovskyy** [comment]
@lili2311 just to verify text with her? Or show how it actually looks ?

**Comment by lili2311** [comment]
@dkontorovskyy just to check the text yep!

**Comment by dkontorovskyy** [comment]
@lili2311 done! Do you want to approve ?

**Pull request merged**
