### PR TITLE
fix: log4shell cmd - add support for log4j 2.16

### PR DESCRIPTION
**Pull request by danlucian**
#### What does this PR do?

Log4j released a new version (2.17) and marked 2.16 as vulnerable to DOS attack.
We updated our data to identify the 2.16 vulnerable versions.

CVE: https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2321524

### CODE REVIEW

**Review by anthogez — COMMENTED** [review]
Some test fixtures?

**Comment by danlucian** [comment]
> Some test fixtures?

Added.

**Review by anthogez — APPROVED** [review]

**Comment by anthogez** [comment]
Small nitpick thing @danlucian , could you propagate your GitHub notes to the commit message body?

`Log4j released a new version (2.17) and marked 2.16 as vulnerable to DOS attack.
We updated our data to identify the 2.16 vulnerable versions.`

CVE: https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2321524

**Comment by anthogez** [comment]
Small nitpick thing @danlucian , could you propagate your GitHub notes to the commit message body?

```

Log4j released a new version (2.17) and marked 2.16 as vulnerable to DOS attack.
We updated our data to identify the 2.16 vulnerable versions.

CVE: https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2321524

```

**Comment by danlucian** [comment]
> Small nitpick thing @danlucian , could you propagate your GitHub notes to the commit message body?
> 
> ```
> 
> Log4j released a new version (2.17) and marked 2.16 as vulnerable to DOS attack.
> We updated our data to identify the 2.16 vulnerable versions.
> 
> CVE: https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2321524
> ```

Sure thing! Added.

**Pull request merged**
