### PR TITLE
feat: support setup.py via new python plugin

### PR DESCRIPTION
**Pull request by miiila**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?
Bumps python plugin version to get support for setup.py. After merging https://github.com/snyk/snyk-python-plugin/pull/62, it would be great to get it into cli.

### CODE REVIEW

**Comment by miiila** [comment]
@julienduchesne FYI, this the step needed to get your changes into snyk cli.

**Comment by julienduchesne** [comment]
Ah nice. I was wondering how to do that. Thanks!
The docker image will have to be adjusted too but I'll handle that

**Comment by dkontorovskyy** [comment]
@miiila it looks like you need to fix types errors

**Comment by dkontorovskyy** [comment]
@miiila maybe this will fix types errors

https://github.com/snyk/snyk-python-plugin/pull/73/files

**Comment by kyegupov** [comment]
I think this has been superseded by https://github.com/snyk/snyk/pull/715

**Pull request closed without merging**
