### PR TITLE
feat: add Dockerfile.python-3.6

### PR DESCRIPTION
**Pull request by VMabille**
#### What does this PR do?
This PR adds aims to have a new snyk-cli image based on a python-3.6 image. 

#### Any background context you want to provide?
Some of the python dependencies we deliver and scan in my projects have hard dependencies on python 3.6.

### CODE REVIEW

**Comment by VMabille** [comment]
I am not too sure why the Danger JS verification failed, is there any way I can get more verbosity?

**Comment by JackuB** [comment]
@VMabille hi, thanks a lot for the PR! Danger (and CircleCI) are not run for fork PRs - e.g. https://github.com/snyk/snyk/pull/1417/checks?check_run_id=1127812982

I've created a new PR https://github.com/snyk/snyk/pull/1420 and just repushed your commit. Will merge #1420 and close this one.

**Comment by VMabille** [comment]
Thanks!

**Comment by JackuB** [comment]
Python 3.6 tag is now available https://hub.docker.com/layers/snyk/snyk-cli/python-3.6/images/sha256-556ab5ef0a1b69a5e124ce4b434e76b978e9305adfd5e4b4e5d4c1e5065d0c2e?context=repo

**Pull request closed without merging**
