### PR TITLE
add a deprecation warning for users using node v6

### PR DESCRIPTION
**Pull request by YashdalfTheGray**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
- Adds an EOL warning at the end of the CLI output for users that are still using Node v6. 

#### Where should the reviewer start?
[src/cli/index.ts:162](https://github.com/YashdalfTheGray/snyk/blob/master/src/cli/index.ts#L162)

##### Positive
- Either spin up a Docker container or use `nvm` to switch to Node.js v6
- Run any `snyk` command
- **Expected** - should see an EOL warning

##### Negative
- Either spin up a Docker container or use `nvm` to switch to a supported version of Node >=v7
- Run any `snyk` command
- **Expected** - should not see an EOL warning

#### Any background context you want to provide?
I saw that there was a `runtime` module and an alert system built already. So I simply append a new alert for Node.js v6 using the new [`runtime.isUsingNode6()`](https://github.com/YashdalfTheGray/snyk/blob/master/src/cli/runtime.ts#L11) function. 

#### What are the relevant tickets?
#787 

##### Node 6

node6

##### Node 8

node8

### CODE REVIEW

**Comment by lili2311** [comment]
Please could you include a screenshot of what this looks like when run on Node 6 and on Node 8?

**Comment by YashdalfTheGray** [comment]
> Please could you include a screenshot of what this looks like when run on Node 6 and on Node 8?

Yeah, sure. I'll do that once I get home tonight if that's okay. I'm on PST.

**Comment by YashdalfTheGray** [comment]
@lili2311 sorry it took so long for me to get this done but I just added the requested images!

**Comment by dkontorovskyy** [comment]
@YashdalfTheGray , thanks much for your contribution!
I will need to merge your changes into temp branch and then open PR into master from it, in order tests to pass. 
Will keep you updated!
And thanks again for contributing!

Cheers,
Daniel

**Comment by YashdalfTheGray** [comment]
Okay, sounds good.

**Pull request merged**
