### PR TITLE
fix: add proxy support when fetching patches

### PR DESCRIPTION
**Pull request by timja-kainos**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
Adds proxy support when fetching patches, see https://github.com/snyk/snyk/pull/112

Let me know if you think this should be refactored into the lib/request/request file, 

#### Any background context you want to provide?
https://github.com/snyk/snyk/pull/112

### CODE REVIEW

**Comment by odinn1984** [comment]
@timja-kainos please run `npm run lint` and fix all of the linting errors and make sure tests are running correctly. Thanks!

**Comment by odinn1984** [comment]
@timja-kainos please make sure that there is only one fix commit that contains the fix with the following format: "fix: what we fixed" also the branch name should be in the format of "fix/what_fixing" 

also, this change needs to be documented as it may cause some un-expected behaviour for users that don't expect this.

**Comment by timja-kainos** [comment]
@odinn1984 The docs say this should work https://snyk.io/docs/faqs/#using-snyk
I partially fixed this a couple of months ago after the migration from `request` to `needle` but I didn't notice that this part wasn't working and other priorities came up.
Are any additional docs changes needed?

**Comment by timja-kainos** [comment]
Superseded by https://github.com/snyk/snyk/pull/122

**Pull request closed without merging**
