### PR TITLE
docs: fix up some of the language

### PR DESCRIPTION
**Pull request by racheyfi**
docs: fix up some of the language

- [X] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
fixes some of the snyk help text

### CODE REVIEW

**Comment by lili2311** [comment]
@racheyfi since you raised a PR via a fork the tests won't run, @aviadatsnyk maybe you can help and re-raise this and cherry-pick the commits?

**Comment by aviadhahami** [comment]
wrong Aviad again @lili2311 :laughing:

**Comment by lili2311** [comment]
Sorry 🙈 will be more careful

**Comment by aviadhahami** [comment]
Closed in favor of https://github.com/snyk/snyk/pull/1056

**Pull request closed without merging**
