### PR TITLE
fix: update to latest node-uuid

### PR DESCRIPTION
**Pull request by jsarenik**
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules
- [ ] Reviewed by @remy (Snyk internal team)
#### What does this PR do?

It updates dependency node-uuid to currently latest version, which uses a more secure enthropy source.
#### Where should the reviewer start?

https://david-dm.org/snyk/snyk
#### How should this be manually tested?

```
$ cd snyk
$ npm install
$ cat node_modules/node-uuid/package.json | grep version
  "version": "1.4.7"
```

---

https://nodesecurity.io/advisories/uuid_insecure-entropy-source-mathrandom
as reported by https://david-dm.org/snyk/snyk

### CODE REVIEW

**Comment by jsarenik** [comment]
These are the last lines from error on Shippable:

```
npm ERR! Linux 3.19.0-51-generic
npm ERR! argv "node" "/root/.nvm/versions/node/v0.12.16/bin/npm" "run" "tap"
npm ERR! node v0.12.16
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! snyk@ tap: `COVERALLS_REPO_TOKEN=0 tap --timeout=180 --cov --coverage-report=text-summary test/*.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snyk@ tap script 'COVERALLS_REPO_TOKEN=0 tap --timeout=180 --cov --coverage-report=text-summary test/*.test.js'.
npm ERR! This is most likely a problem with the snyk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     COVERALLS_REPO_TOKEN=0 tap --timeout=180 --cov --coverage-report=text-summary test/*.test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snyk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls snyk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/src/github.com/Snyk/snyk/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by jsarenik** [comment]
Do you use such an old node still somewhere? Otherwise it could be disabled for the tests.

**Comment by jsarenik** [comment]
I am trying to match the Shippable settings to those of Travis. No success yet.

**Comment by jsarenik** [comment]
Locally the tests go through fine, like on Travis.

**Comment by adrukh** [comment]
@jsarenik thanks for the PR!
Please move the shippable change out of it (so the content matches the title), I will deal with shippable in a different commit.

**Comment by jsarenik** [comment]
Here it is.

**Comment by adrukh** [comment]
We're good and this is now included, see https://github.com/Snyk/snyk/commit/063eaf7ea863a348a7a6685d0409806a68e6a050

Done outside of this PR's scope due to our internal release process.

**Pull request closed without merging**
